### ISSUE TITLE
DaLi generated output results in RP2TypeError: Parameter 'unique_id' has non-string value

### ISSUE THREAD

**Issue by stevendavis** [eprbell/rp2#39]
Not sure if this is a problem with DaLi, RP2, or something I'm doing wrong.

DaLi input is a manual in_csv_file with a unique id consisting of all digits, 61891576412, no decimal point.
DaLi runs successfully and generates the crypto_data.ods output file.
When RP2 runs it raises this error: 
rp2.rp2_error.RP2TypeError: Parameter 'unique_id' has non-string value 61891576412.0

**Comment by eprbell** [comment]
Oh, that's interesting: could you post the full stack?

**Comment by stevendavis** [comment]
Sure, here you go...

Traceback (most recent call last):
  File "C:\Users\me\.conda\envs\dali-rp2\lib\site-packages\rp2\rp2_main.py", line 93, in _rp2_main_internal
    input_data: InputData = parse_ods(configuration=configuration, asset=asset, input_file_handle=input_file_handle)
  File "C:\Users\me\.conda\envs\dali-rp2\lib\site-packages\rp2\ods_parser.py", line 128, in parse_ods
    _create_and_process_transaction(
  File "C:\Users\me\.conda\envs\dali-rp2\lib\site-packages\rp2\ods_parser.py", line 168, in _create_and_process_transaction
    transaction: AbstractTransaction = _create_transaction(configuration, current_table_type, internal_id, row_values)
  File "C:\Users\me\.conda\envs\dali-rp2\lib\site-packages\rp2\ods_parser.py", line 284, in _create_transaction
    transaction = InTransaction(**argument_pack)
  File "C:\Users\me\.conda\envs\dali-rp2\lib\site-packages\rp2\in_transaction.py", line 52, in __init__
    super().__init__(configuration, timestamp, asset, transaction_type, spot_price, internal_id, unique_id, notes)
  File "C:\Users\me\.conda\envs\dali-rp2\lib\site-packages\rp2\abstract_transaction.py", line 43, in __init__
    self.__unique_id: str = configuration.type_check_string("unique_id", unique_id) if unique_id is not None else ""
  File "C:\Users\me\.conda\envs\dali-rp2\lib\site-packages\rp2\configuration.py", line 230, in type_check_string
    raise RP2TypeError(f"Parameter '{name}' has non-string value {repr(value)}")
rp2.rp2_error.RP2TypeError: Parameter 'unique_id' has non-string value 61891576412.0

**Comment by eprbell** [comment]
Fixed: could you retry with the latest version?

**Comment by eprbell** [comment]
Thanks for reporting! This was a relatively rare corner case: it would never have been fixed without your help!

**Comment by stevendavis** [comment]
Working now.  Thank you for the quick fix.
